name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 1: Set up SSH
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.HOSTINGER_SSH_KEY }}

    # Step 2: Add Hostinger VPS to known_hosts
    - name: Add Hostinger VPS to known_hosts
      run: |
        ssh-keyscan -H 82.180.154.206 >> ~/.ssh/known_hosts

    # Step 3: Deploy Laravel (Back)
    - name: Copy Laravel files (back)
      run: |
        scp -r ./back/* root@82.180.154.206:/var/www/fujtek.com/html/back/

    - name: Install Composer dependencies and migrate (Laravel back)
      run: |
        ssh root@82.180.154.206 "cd /var/www/fujtek.com/html/back && composer install --no-dev --optimize-autoloader && php artisan migrate --force"

    # Step 4: Deploy Next.js (Front)
    - name: Copy Next.js files (front)
      run: |
        scp -r ./front/* root@82.180.154.206:/var/www/fujtek.com/html/front/

    - name: Install Node.js dependencies and build (Next.js front)
      run: |
        ssh root@82.180.154.206 "cd /var/www/fujtek.com/html/front && npm install && npm run build"

    # Step 5: Restart Next.js App using PM2
    - name: Restart Next.js app with PM2
      run: |
        ssh root@82.180.154.206 "cd /var/www/fujtek.com/html/front && pm2 restart nextjs-app"

    # Step 6: Restart Nginx
    - name: Restart Nginx
      run: |
        ssh root@82.180.154.206 "sudo systemctl restart nginx"
